name: CI-CD
on:
  push:
    branches: ["deployment", "main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1
        run: echo "Construir a imagem da aplicação"
      - name: Passo 2
        run: echo "Publicar imagem no Docker Hub"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 01
        run: echo "Deploy da aplicação"
    
