name: CI-CD
on:
  push:
    branches: ["deployment", "main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código conte
        uses: actions/checkout@v4.1.7

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Passo 1
        run: echo "Construir a imagem da aplicação"
      - name: Passo 2
        run: echo "Publicar imagem no Docker Hub"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 01
        run: echo "Deploy da aplicação"
    
